# Generated by Django 6.0.1 on 2026-01-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='state',
            field=models.CharField(choices=[('SAFE', 'Safe'), ('BE_CAREFUL', 'Be careful'), ('UNSAFE', 'Unsafe')], default='BE_CAREFUL', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='risk_level',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='unknown', max_length=20),
        ),
    ]
