# Generated by Django 6.0.1 on 2026-01-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_url', models.URLField(max_length=2048, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('unknown', 'unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='unknown', max_length=20)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checks', models.JSONField(blank=True, default=dict)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanner.url')),
            ],
        ),
    ]
